
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AccountCreationSuccess': typeof import("../components/AccountCreationSuccess.vue")['default']
    'AuthCarousel': typeof import("../components/AuthCarousel.vue")['default']
    'Carousel': typeof import("../components/Carousel.vue")['default']
    'CreatePasscodeForm': typeof import("../components/CreatePasscodeForm.vue")['default']
    'CreatePassword': typeof import("../components/CreatePassword.vue")['default']
    'DashboardOverview': typeof import("../components/DashboardOverview.vue")['default']
    'ExistingUserLogin': typeof import("../components/ExistingUserLogin.vue")['default']
    'ForgotPassword': typeof import("../components/ForgotPassword.vue")['default']
    'ForgotPasswordVerificationForm': typeof import("../components/ForgotPasswordVerificationForm.vue")['default']
    'LoginForm': typeof import("../components/LoginForm.vue")['default']
    'PasscodeRecoveryForm': typeof import("../components/PasscodeRecoveryForm.vue")['default']
    'PasswordRecovery': typeof import("../components/PasswordRecovery.vue")['default']
    'PaymentBankAccountComponent': typeof import("../components/Payment/BankAccountComponent.vue")['default']
    'PaymentBankAccountForm': typeof import("../components/Payment/BankAccountForm.vue")['default']
    'PaymentBankCard': typeof import("../components/Payment/BankCard.vue")['default']
    'PaymentCardsList': typeof import("../components/Payment/CardsList.vue")['default']
    'PaymentFilterButton': typeof import("../components/Payment/FilterButton.vue")['default']
    'PaymentFilterModal': typeof import("../components/Payment/FilterModal.vue")['default']
    'PaymentTabNavigation': typeof import("../components/Payment/TabNavigation.vue")['default']
    'PaymentTransactionList': typeof import("../components/Payment/TransactionList.vue")['default']
    'PaymentTransactionModal': typeof import("../components/Payment/TransactionModal.vue")['default']
    'PaymentWalletActions': typeof import("../components/Payment/WalletActions.vue")['default']
    'PaymentWalletCard': typeof import("../components/Payment/WalletCard.vue")['default']
    'ProfileEmploymentDetails': typeof import("../components/Profile/EmploymentDetails.vue")['default']
    'ProfileGovernmentId': typeof import("../components/Profile/GovernmentId.vue")['default']
    'ProfileNextOfKin': typeof import("../components/Profile/NextOfKin.vue")['default']
    'ProfilePersonalInfo': typeof import("../components/Profile/PersonalInfo.vue")['default']
    'ProfilePinUpdate': typeof import("../components/Profile/PinUpdate.vue")['default']
    'ProfileTabs': typeof import("../components/Profile/Tabs.vue")['default']
    'ProfileUpdatePasscode': typeof import("../components/Profile/UpdatePasscode.vue")['default']
    'ProfileUpdateSecurity': typeof import("../components/Profile/UpdateSecurity.vue")['default']
    'ProfileUserProfile': typeof import("../components/Profile/UserProfile.vue")['default']
    'ReEnterPinForm': typeof import("../components/ReEnterPinForm.vue")['default']
    'SignupForm': typeof import("../components/SignupForm.vue")['default']
    'SignupSuccess': typeof import("../components/SignupSuccess.vue")['default']
    'TransactionPinSetup': typeof import("../components/TransactionPinSetup.vue")['default']
    'UserLogin': typeof import("../components/UserLogin.vue")['default']
    'VerificationForm': typeof import("../components/VerificationForm.vue")['default']
    'CoreBaseModal': typeof import("../components/core/BaseModal.vue")['default']
    'CoreCountryCodeModal': typeof import("../components/core/CountryCodeModal.vue")['default']
    'CoreToast': typeof import("../components/core/Toast.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAccountCreationSuccess': typeof import("../components/AccountCreationSuccess.vue")['default']
    'LazyAuthCarousel': typeof import("../components/AuthCarousel.vue")['default']
    'LazyCarousel': typeof import("../components/Carousel.vue")['default']
    'LazyCreatePasscodeForm': typeof import("../components/CreatePasscodeForm.vue")['default']
    'LazyCreatePassword': typeof import("../components/CreatePassword.vue")['default']
    'LazyDashboardOverview': typeof import("../components/DashboardOverview.vue")['default']
    'LazyExistingUserLogin': typeof import("../components/ExistingUserLogin.vue")['default']
    'LazyForgotPassword': typeof import("../components/ForgotPassword.vue")['default']
    'LazyForgotPasswordVerificationForm': typeof import("../components/ForgotPasswordVerificationForm.vue")['default']
    'LazyLoginForm': typeof import("../components/LoginForm.vue")['default']
    'LazyPasscodeRecoveryForm': typeof import("../components/PasscodeRecoveryForm.vue")['default']
    'LazyPasswordRecovery': typeof import("../components/PasswordRecovery.vue")['default']
    'LazyPaymentBankAccountComponent': typeof import("../components/Payment/BankAccountComponent.vue")['default']
    'LazyPaymentBankAccountForm': typeof import("../components/Payment/BankAccountForm.vue")['default']
    'LazyPaymentBankCard': typeof import("../components/Payment/BankCard.vue")['default']
    'LazyPaymentCardsList': typeof import("../components/Payment/CardsList.vue")['default']
    'LazyPaymentFilterButton': typeof import("../components/Payment/FilterButton.vue")['default']
    'LazyPaymentFilterModal': typeof import("../components/Payment/FilterModal.vue")['default']
    'LazyPaymentTabNavigation': typeof import("../components/Payment/TabNavigation.vue")['default']
    'LazyPaymentTransactionList': typeof import("../components/Payment/TransactionList.vue")['default']
    'LazyPaymentTransactionModal': typeof import("../components/Payment/TransactionModal.vue")['default']
    'LazyPaymentWalletActions': typeof import("../components/Payment/WalletActions.vue")['default']
    'LazyPaymentWalletCard': typeof import("../components/Payment/WalletCard.vue")['default']
    'LazyProfileEmploymentDetails': typeof import("../components/Profile/EmploymentDetails.vue")['default']
    'LazyProfileGovernmentId': typeof import("../components/Profile/GovernmentId.vue")['default']
    'LazyProfileNextOfKin': typeof import("../components/Profile/NextOfKin.vue")['default']
    'LazyProfilePersonalInfo': typeof import("../components/Profile/PersonalInfo.vue")['default']
    'LazyProfilePinUpdate': typeof import("../components/Profile/PinUpdate.vue")['default']
    'LazyProfileTabs': typeof import("../components/Profile/Tabs.vue")['default']
    'LazyProfileUpdatePasscode': typeof import("../components/Profile/UpdatePasscode.vue")['default']
    'LazyProfileUpdateSecurity': typeof import("../components/Profile/UpdateSecurity.vue")['default']
    'LazyProfileUserProfile': typeof import("../components/Profile/UserProfile.vue")['default']
    'LazyReEnterPinForm': typeof import("../components/ReEnterPinForm.vue")['default']
    'LazySignupForm': typeof import("../components/SignupForm.vue")['default']
    'LazySignupSuccess': typeof import("../components/SignupSuccess.vue")['default']
    'LazyTransactionPinSetup': typeof import("../components/TransactionPinSetup.vue")['default']
    'LazyUserLogin': typeof import("../components/UserLogin.vue")['default']
    'LazyVerificationForm': typeof import("../components/VerificationForm.vue")['default']
    'LazyCoreBaseModal': typeof import("../components/core/BaseModal.vue")['default']
    'LazyCoreCountryCodeModal': typeof import("../components/core/CountryCodeModal.vue")['default']
    'LazyCoreToast': typeof import("../components/core/Toast.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AccountCreationSuccess: typeof import("../components/AccountCreationSuccess.vue")['default']
export const AuthCarousel: typeof import("../components/AuthCarousel.vue")['default']
export const Carousel: typeof import("../components/Carousel.vue")['default']
export const CreatePasscodeForm: typeof import("../components/CreatePasscodeForm.vue")['default']
export const CreatePassword: typeof import("../components/CreatePassword.vue")['default']
export const DashboardOverview: typeof import("../components/DashboardOverview.vue")['default']
export const ExistingUserLogin: typeof import("../components/ExistingUserLogin.vue")['default']
export const ForgotPassword: typeof import("../components/ForgotPassword.vue")['default']
export const ForgotPasswordVerificationForm: typeof import("../components/ForgotPasswordVerificationForm.vue")['default']
export const LoginForm: typeof import("../components/LoginForm.vue")['default']
export const PasscodeRecoveryForm: typeof import("../components/PasscodeRecoveryForm.vue")['default']
export const PasswordRecovery: typeof import("../components/PasswordRecovery.vue")['default']
export const PaymentBankAccountComponent: typeof import("../components/Payment/BankAccountComponent.vue")['default']
export const PaymentBankAccountForm: typeof import("../components/Payment/BankAccountForm.vue")['default']
export const PaymentBankCard: typeof import("../components/Payment/BankCard.vue")['default']
export const PaymentCardsList: typeof import("../components/Payment/CardsList.vue")['default']
export const PaymentFilterButton: typeof import("../components/Payment/FilterButton.vue")['default']
export const PaymentFilterModal: typeof import("../components/Payment/FilterModal.vue")['default']
export const PaymentTabNavigation: typeof import("../components/Payment/TabNavigation.vue")['default']
export const PaymentTransactionList: typeof import("../components/Payment/TransactionList.vue")['default']
export const PaymentTransactionModal: typeof import("../components/Payment/TransactionModal.vue")['default']
export const PaymentWalletActions: typeof import("../components/Payment/WalletActions.vue")['default']
export const PaymentWalletCard: typeof import("../components/Payment/WalletCard.vue")['default']
export const ProfileEmploymentDetails: typeof import("../components/Profile/EmploymentDetails.vue")['default']
export const ProfileGovernmentId: typeof import("../components/Profile/GovernmentId.vue")['default']
export const ProfileNextOfKin: typeof import("../components/Profile/NextOfKin.vue")['default']
export const ProfilePersonalInfo: typeof import("../components/Profile/PersonalInfo.vue")['default']
export const ProfilePinUpdate: typeof import("../components/Profile/PinUpdate.vue")['default']
export const ProfileTabs: typeof import("../components/Profile/Tabs.vue")['default']
export const ProfileUpdatePasscode: typeof import("../components/Profile/UpdatePasscode.vue")['default']
export const ProfileUpdateSecurity: typeof import("../components/Profile/UpdateSecurity.vue")['default']
export const ProfileUserProfile: typeof import("../components/Profile/UserProfile.vue")['default']
export const ReEnterPinForm: typeof import("../components/ReEnterPinForm.vue")['default']
export const SignupForm: typeof import("../components/SignupForm.vue")['default']
export const SignupSuccess: typeof import("../components/SignupSuccess.vue")['default']
export const TransactionPinSetup: typeof import("../components/TransactionPinSetup.vue")['default']
export const UserLogin: typeof import("../components/UserLogin.vue")['default']
export const VerificationForm: typeof import("../components/VerificationForm.vue")['default']
export const CoreBaseModal: typeof import("../components/core/BaseModal.vue")['default']
export const CoreCountryCodeModal: typeof import("../components/core/CountryCodeModal.vue")['default']
export const CoreToast: typeof import("../components/core/Toast.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAccountCreationSuccess: typeof import("../components/AccountCreationSuccess.vue")['default']
export const LazyAuthCarousel: typeof import("../components/AuthCarousel.vue")['default']
export const LazyCarousel: typeof import("../components/Carousel.vue")['default']
export const LazyCreatePasscodeForm: typeof import("../components/CreatePasscodeForm.vue")['default']
export const LazyCreatePassword: typeof import("../components/CreatePassword.vue")['default']
export const LazyDashboardOverview: typeof import("../components/DashboardOverview.vue")['default']
export const LazyExistingUserLogin: typeof import("../components/ExistingUserLogin.vue")['default']
export const LazyForgotPassword: typeof import("../components/ForgotPassword.vue")['default']
export const LazyForgotPasswordVerificationForm: typeof import("../components/ForgotPasswordVerificationForm.vue")['default']
export const LazyLoginForm: typeof import("../components/LoginForm.vue")['default']
export const LazyPasscodeRecoveryForm: typeof import("../components/PasscodeRecoveryForm.vue")['default']
export const LazyPasswordRecovery: typeof import("../components/PasswordRecovery.vue")['default']
export const LazyPaymentBankAccountComponent: typeof import("../components/Payment/BankAccountComponent.vue")['default']
export const LazyPaymentBankAccountForm: typeof import("../components/Payment/BankAccountForm.vue")['default']
export const LazyPaymentBankCard: typeof import("../components/Payment/BankCard.vue")['default']
export const LazyPaymentCardsList: typeof import("../components/Payment/CardsList.vue")['default']
export const LazyPaymentFilterButton: typeof import("../components/Payment/FilterButton.vue")['default']
export const LazyPaymentFilterModal: typeof import("../components/Payment/FilterModal.vue")['default']
export const LazyPaymentTabNavigation: typeof import("../components/Payment/TabNavigation.vue")['default']
export const LazyPaymentTransactionList: typeof import("../components/Payment/TransactionList.vue")['default']
export const LazyPaymentTransactionModal: typeof import("../components/Payment/TransactionModal.vue")['default']
export const LazyPaymentWalletActions: typeof import("../components/Payment/WalletActions.vue")['default']
export const LazyPaymentWalletCard: typeof import("../components/Payment/WalletCard.vue")['default']
export const LazyProfileEmploymentDetails: typeof import("../components/Profile/EmploymentDetails.vue")['default']
export const LazyProfileGovernmentId: typeof import("../components/Profile/GovernmentId.vue")['default']
export const LazyProfileNextOfKin: typeof import("../components/Profile/NextOfKin.vue")['default']
export const LazyProfilePersonalInfo: typeof import("../components/Profile/PersonalInfo.vue")['default']
export const LazyProfilePinUpdate: typeof import("../components/Profile/PinUpdate.vue")['default']
export const LazyProfileTabs: typeof import("../components/Profile/Tabs.vue")['default']
export const LazyProfileUpdatePasscode: typeof import("../components/Profile/UpdatePasscode.vue")['default']
export const LazyProfileUpdateSecurity: typeof import("../components/Profile/UpdateSecurity.vue")['default']
export const LazyProfileUserProfile: typeof import("../components/Profile/UserProfile.vue")['default']
export const LazyReEnterPinForm: typeof import("../components/ReEnterPinForm.vue")['default']
export const LazySignupForm: typeof import("../components/SignupForm.vue")['default']
export const LazySignupSuccess: typeof import("../components/SignupSuccess.vue")['default']
export const LazyTransactionPinSetup: typeof import("../components/TransactionPinSetup.vue")['default']
export const LazyUserLogin: typeof import("../components/UserLogin.vue")['default']
export const LazyVerificationForm: typeof import("../components/VerificationForm.vue")['default']
export const LazyCoreBaseModal: typeof import("../components/core/BaseModal.vue")['default']
export const LazyCoreCountryCodeModal: typeof import("../components/core/CountryCodeModal.vue")['default']
export const LazyCoreToast: typeof import("../components/core/Toast.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
